---
name: PR auto-merge

on:
  workflow_run:
    workflows: [Test]
    types: [completed]

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@eb68b061739cb9d81564f8e812d0b3c45f0fb09a"  # v0.15.5
        env:
          GITHUB_TOKEN: "${{ secrets.UNDEFINED_TOKEN || secrets.REPO_TOKEN || secrets.GITHUB_TOKEN }}"
          MERGE_ERROR_FAIL: true
          MErGE_DELETE_BRANCH: true
          MERGE_LABELS: "automerge"
          MERGE_METHOD: "merge"
