---
name: Release

env:
  ENABLE_PYPI_PUBLISH: false
  ENABLE_TEST_PYPI_PUBLISH: false
  RELEASE_POETRY_VERSION: "1.3"

on:
  push:
    tags:
      - '*'

jobs:
  Publish:
    name: Publish package for ${{ github.ref_name }}

    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest

    steps:
      - name: 💾 Check out repository
        uses: actions/checkout@v3

      - name: 📜 Fetch full repository history for unit tests
        run: git fetch --unshallow

      - name: 🐍 Build and test Python project with Poetry
        uses: ./.github/workflows/actions/python-poetry

      - name: 🔼 Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        if: ${{ env.ENABLE_TEST_PYPI_PUBLISH == 'true' }}
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          skip_existing: true

      - name: ☢️ Publish to PyPI
        if: ${{ env.ENABLE_PYPI_PUBLISH == 'true' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
